---
title: "Homework 1 Solution"
output: github_document
name: Sihan Qiu
---

```{r setup, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
set.seed(1)
```


## Q1
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

```{r}
log_sample = function(data) {
  log_data = data |>
    slice_sample(n = nrow(data), replace = TRUE)
    fit = lm(tmax ~ tmin, data = log_data)
    r_squared = broom::glance(fit)[["r.squared"]]
  
    coefficients = broom::tidy(fit)
    log_beta = log(coefficients[["estimate"]][1] * coefficients[["estimate"]][2])
  
    return(tibble(r_squared = r_squared, log_beta = log_beta))
}
```

```{r}
n_log = 5000

log_results = tibble(iteration = 1:n_log) |>
  mutate(
    result = map(iteration, ~ log_sample(weather_df))
  ) |>
  unnest(result)
```

```{r}
ggplot(log_results, aes(x = log_beta)) +
  geom_density() +
  labs(title = "Distribution of log(β0 * β1) from Bootstrap Samples",
       x = "log(β0 * β1)",
       y = "Density")

```
description:
it seems like it follows a normal distribution.

```{r}
ci_r_sq = quantile(log_results[["r_squared"]], c(0.025, 0.975))
ci_log_beta = quantile(log_results[["log_beta"]], c(0.025, 0.975))
```

```{r}
ci_df = tibble(
    metric = c("R-squared", "log(β0 * β1)"),
    estimate = c(mean(log_results[["r_squared"]]), mean(log_results[["log_beta"]])),
    conf.low = c(ci_r_sq[1], ci_log_beta[1]),
    conf.high = c(ci_r_sq[2], ci_log_beta[2])
  )
```

```{r}
ci_plot = 
  ggplot(ci_df, aes(x = metric, y = estimate)) +
    geom_point(size = 3) +
    geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2) +
    labs(
      title = "95% Confidence Intervals",
      x = "Metric",
      y = "Estimate"
    ) +
    theme_minimal()
ci_plot
```

## Q2
```{r}

```

